package com.harman.hkwirelessapi;

/**
 * Created by lee on 15/5/11.
 */
public enum HKErrorCode {
    ERROR_TIMEOUT,
    ERROR_DISC_TIMEOUT,
    ERROR_SYNC_TIMEOUT,
    ERROR_STREAM_TIMEOUT,
    ERROR_DATA_TIMEOUT,
    ERROR_LOST_CONNECTION,
    ERROR_INCOMPATIBLE_VERSION,
    ERROR_MEDIA_UNSUPPORTED,
    ERROR_INVALID_DESTINATION,
    ERROR_LEFT_SESSION,
    ERROR_BAD_LOGIC,
    ERROR_CONFIG_FAILURE,
    ERROR_UNDEFINED
}
